version: '3.8'
services:
  Store_management:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=store
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3306:3306'
volumes:
  db:
    driver: local